[tool.poetry]
name = "phd"
version = "0.1.0"
description = ""
authors = ["Ivan Dubrovin <books.booksovich@yandex.com>"]
license = "GNU GPLv3"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
